on:
  push:
  pull_request:

name: Test creating bundles

jobs:
  Build:
    runs-on: macOS-latest
    name: macOS-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create CRAN bundle
        run: ./cranbundle.sh

      - name: "Upload bundle archive"
        uses: actions/upload-artifact@v2
        with:
          name: archive
          path: archive

      - name: Create bundles
        run: |
          for f in *.sh; do
            echo "::group::Testing $f"
            echo "Processing $f formula..."
            ./$f || true
            echo "::endgroup::"
          done
