on:
  workflow_dispatch:

name: Create and upload CRAN bundles

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create CRAN bundle
        run: ./cranbundle.sh

      - name: "Upload bundle archive"
        uses: actions/upload-artifact@v3
        with:
          name: archive
          path: archive
