on:
  workflow_dispatch:
    inputs:
      library:
        description: 'Which library to bundle'
        required: true

name: Release a single library bundle

jobs:
  Build:
    runs-on: macos-13
    steps:
      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global user.email '121622595+jeroen[bot]@users.noreply.github.com'
          git config --global user.name  'Jeroen (via CI)'

      - name: Checkout
        uses: actions/checkout@v4

#      - id: reset
#        name: Reset homebrew to bigsur
#        run: ./lib/bigsur-reset.sh

      - id: bundle
        name: Create bundles
        run: ./${{ github.event.inputs.library }}.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.library }}-${{ steps.bundle.outputs.version }}
          files: dist/*.xz
