on:
  workflow_dispatch:
    inputs:
      library:
        description: 'Which library to bundle'
        required: false
      save:
        description: 'Save artifacts'
        required: false

name: Test creating bundles

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, macos-12 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create bundles
        run: |
          if [ "${{ github.event.inputs.library }}" ]; then
            ./${{ github.event.inputs.library }}.sh
          else
            for f in *.sh; do
              STATUS="OK"
              ./$f > /tmp/outlog 2>&1 || STATUS="FAILED"
              echo "::group::Testing $f $STATUS"
              cat /tmp/outlog
              echo "::endgroup::"
            done
          fi

      - uses: actions/upload-artifact@v3
        if: ${{ github.event.inputs.save }}
        with:
          name: archive
          path: archive/*/*.xz
